-- Animorank Database Setup Script
-- Run this in the Supabase SQL Editor to create all required tables.

-- Teacher table (must be created before Problem_set due to FK)
CREATE TABLE public."Teacher" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    email text NOT NULL,
    profile_url text,
    CONSTRAINT "Teacher_pkey" PRIMARY KEY (email)
);

-- Student table
CREATE TABLE public."Student" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    email text NOT NULL,
    profile_url text,
    CONSTRAINT "Student_pkey" PRIMARY KEY (email)
);

-- Teacher_list (email allowlist that determines teacher vs student role)
CREATE TABLE public."Teacher_list" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email text NOT NULL,
    CONSTRAINT "Teacher_list_pkey" PRIMARY KEY (id)
);

ALTER TABLE public."Teacher_list" ENABLE ROW LEVEL SECURITY;

-- Problem_set
CREATE TABLE public."Problem_set" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    description text,
    title text NOT NULL,
    owner_email text NOT NULL,
    auto_accept boolean DEFAULT false,
    is_solo_problem boolean DEFAULT false,
    is_global boolean DEFAULT false,
    CONSTRAINT "Problem_set_pkey" PRIMARY KEY (id),
    CONSTRAINT "Problem_set_owner_email_fkey" FOREIGN KEY (owner_email)
        REFERENCES public."Teacher"(email) ON UPDATE CASCADE
);

-- Problem
CREATE TABLE public."Problem" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    body text,
    problem_name text NOT NULL,
    starter_code text,
    language character varying NOT NULL,
    problem_set bigint NOT NULL,
    CONSTRAINT "Problem_pkey" PRIMARY KEY (id),
    CONSTRAINT "Problem_problem_set_fkey" FOREIGN KEY (problem_set)
        REFERENCES public."Problem_set"(id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Session (tracks student code history per problem)
CREATE TABLE public."Session" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    problem_id bigint NOT NULL,
    student_email text NOT NULL,
    last_state text,
    history text,
    CONSTRAINT "Session_pkey" PRIMARY KEY (id),
    CONSTRAINT "Session_problem_id_fkey" FOREIGN KEY (problem_id)
        REFERENCES public."Problem"(id) ON UPDATE CASCADE,
    CONSTRAINT "Session_student_email_fkey" FOREIGN KEY (student_email)
        REFERENCES public."Student"(email) ON UPDATE CASCADE
);

-- Subscription (student subscriptions to problem sets)
CREATE TABLE public."Subscription" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    problem_set bigint NOT NULL,
    student_email text NOT NULL,
    status text,
    CONSTRAINT "Subscription_pkey" PRIMARY KEY (id),
    CONSTRAINT "Subscription_problem_set_fkey" FOREIGN KEY (problem_set)
        REFERENCES public."Problem_set"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT "Subscription_student_email_fkey" FOREIGN KEY (student_email)
        REFERENCES public."Student"(email) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Pset_statistics (problem set statistics, FK to Problem_set)
CREATE TABLE public."Pset_statistics" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    number_students bigint DEFAULT 0,
    total_problems bigint DEFAULT 0,
    CONSTRAINT "Pset_statistics_pkey" PRIMARY KEY (id),
    CONSTRAINT "Pset_statistics_id_fkey" FOREIGN KEY (id)
        REFERENCES public."Problem_set"(id) ON UPDATE CASCADE ON DELETE SET NULL
);
