//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        Problem: {
            name: "Problem",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }],
                    default: ExpressionUtils.call("uuid")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                description: {
                    name: "description",
                    type: "String"
                },
                language: {
                    name: "language",
                    type: "Language",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("C") }] }],
                    default: "C"
                },
                starter_code: {
                    name: "starter_code",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }],
                    default: ""
                },
                visible: {
                    name: "visible",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }],
                    default: true
                },
                problem_set_id: {
                    name: "problem_set_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "problem_set"
                    ]
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "problems", fields: ["problem_set_id"], references: ["id"], onDelete: "Cascade" }
                },
                practice_sessions: {
                    name: "practice_sessions",
                    type: "PracticeSession",
                    array: true,
                    relation: { opposite: "problem" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }],
                    default: ExpressionUtils.call("now")
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }]
                },
                problemTestCases: {
                    name: "problemTestCases",
                    type: "ProblemTestCase",
                    array: true,
                    relation: { opposite: "problem" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProblemTestCase: {
            name: "ProblemTestCase",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }],
                    default: ExpressionUtils.call("uuid")
                },
                type: {
                    name: "type",
                    type: "ProblemTestCaseType",
                    isDiscriminator: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("FunctionOutputTestCase") }] }],
                    default: "FunctionOutputTestCase"
                },
                public: {
                    name: "public",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }],
                    default: true
                },
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "problem"
                    ]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "problemTestCases", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }],
                    default: ExpressionUtils.call("now")
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }]
                }
            },
            attributes: [
                { name: "@@delegate", args: [{ name: "discriminator", value: ExpressionUtils.field("type") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            },
            isDelegate: true,
            subModels: ["FunctionOutputTestCase", "ProgramIOTestCase", "CustomTestCase"]
        },
        FunctionOutputTestCase: {
            name: "FunctionOutputTestCase",
            baseModel: "ProblemTestCase",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }],
                    default: ExpressionUtils.call("uuid")
                },
                type: {
                    name: "type",
                    type: "ProblemTestCaseType",
                    originModel: "ProblemTestCase",
                    isDiscriminator: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("FunctionOutputTestCase") }] }],
                    default: "FunctionOutputTestCase"
                },
                public: {
                    name: "public",
                    type: "Boolean",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }],
                    default: true
                },
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "problem"
                    ]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "problemTestCases", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }],
                    default: ExpressionUtils.call("now")
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }]
                },
                parameters: {
                    name: "parameters",
                    type: "CTypeWithValue",
                    array: true,
                    attributes: [{ name: "@json" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("[]") }] }],
                    default: "[]"
                },
                expected_output: {
                    name: "expected_output",
                    type: "CTypeWithValue",
                    attributes: [{ name: "@json" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{\"base\": \"INT\"}") }] }],
                    default: "{\"base\": \"INT\"}"
                },
                operator: {
                    name: "operator",
                    type: "ProblemTestCaseOperator",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("EQUAL") }] }],
                    default: "EQUAL"
                },
                function_name: {
                    name: "function_name",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }],
                    default: ""
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProgramIOTestCase: {
            name: "ProgramIOTestCase",
            baseModel: "ProblemTestCase",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }],
                    default: ExpressionUtils.call("uuid")
                },
                type: {
                    name: "type",
                    type: "ProblemTestCaseType",
                    originModel: "ProblemTestCase",
                    isDiscriminator: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("FunctionOutputTestCase") }] }],
                    default: "FunctionOutputTestCase"
                },
                public: {
                    name: "public",
                    type: "Boolean",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }],
                    default: true
                },
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "problem"
                    ]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "problemTestCases", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }],
                    default: ExpressionUtils.call("now")
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }]
                },
                input: {
                    name: "input",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }],
                    default: ""
                },
                output: {
                    name: "output",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }],
                    default: ""
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        CustomTestCase: {
            name: "CustomTestCase",
            baseModel: "ProblemTestCase",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }],
                    default: ExpressionUtils.call("uuid")
                },
                type: {
                    name: "type",
                    type: "ProblemTestCaseType",
                    originModel: "ProblemTestCase",
                    isDiscriminator: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("FunctionOutputTestCase") }] }],
                    default: "FunctionOutputTestCase"
                },
                public: {
                    name: "public",
                    type: "Boolean",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }],
                    default: true
                },
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "problem"
                    ]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "problemTestCases", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }],
                    default: ExpressionUtils.call("now")
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }]
                },
                test_code: {
                    name: "test_code",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }],
                    default: ""
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProblemSet: {
            name: "ProblemSet",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }],
                    default: ExpressionUtils.call("uuid")
                },
                description: {
                    name: "description",
                    type: "String",
                    optional: true
                },
                title: {
                    name: "title",
                    type: "String"
                },
                owner_id: {
                    name: "owner_id",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                owner: {
                    name: "owner",
                    type: "Teacher",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("owner_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }],
                    relation: { opposite: "problem_set", fields: ["owner_id"], references: ["id"], onDelete: "SetNull" }
                },
                auto_accept: {
                    name: "auto_accept",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                is_global: {
                    name: "is_global",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                problems: {
                    name: "problems",
                    type: "Problem",
                    array: true,
                    relation: { opposite: "problem_set" }
                },
                subscriptions: {
                    name: "subscriptions",
                    type: "Subscription",
                    array: true,
                    relation: { opposite: "problem_set" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }],
                    default: ExpressionUtils.call("now")
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        PracticeSession: {
            name: "PracticeSession",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }],
                    default: ExpressionUtils.call("uuid")
                },
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "problem"
                    ]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "practice_sessions", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                student_id: {
                    name: "student_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "student"
                    ]
                },
                student: {
                    name: "student",
                    type: "Student",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("student_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "practice_sessions", fields: ["student_id"], references: ["id"], onDelete: "Cascade" }
                },
                done: {
                    name: "done",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                previous_code: {
                    name: "previous_code",
                    type: "String"
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }],
                    default: ExpressionUtils.call("now")
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }]
                },
                practice_history_entries: {
                    name: "practice_history_entries",
                    type: "PracticeHistoryEntry",
                    array: true,
                    relation: { opposite: "practice_session" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        PracticeHistoryEntry: {
            name: "PracticeHistoryEntry",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }],
                    default: ExpressionUtils.call("uuid")
                },
                timestamp: {
                    name: "timestamp",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }],
                    default: ExpressionUtils.call("now")
                },
                type: {
                    name: "type",
                    type: "HistoryEntryType"
                },
                data: {
                    name: "data",
                    type: "Json"
                },
                practice_session_id: {
                    name: "practice_session_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "practice_session"
                    ]
                },
                practice_session: {
                    name: "practice_session",
                    type: "PracticeSession",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("practice_session_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "practice_history_entries", fields: ["practice_session_id"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Student: {
            name: "Student",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }],
                    default: ExpressionUtils.call("uuid"),
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "student", fields: ["id"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                practice_sessions: {
                    name: "practice_sessions",
                    type: "PracticeSession",
                    array: true,
                    relation: { opposite: "student" }
                },
                subscription: {
                    name: "subscription",
                    type: "Subscription",
                    array: true,
                    relation: { opposite: "student" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Subscription: {
            name: "Subscription",
            fields: {
                problem_set_id: {
                    name: "problem_set_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "problem_set"
                    ]
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "subscriptions", fields: ["problem_set_id"], references: ["id"], onDelete: "Cascade" }
                },
                student_id: {
                    name: "student_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "student"
                    ]
                },
                student: {
                    name: "student",
                    type: "Student",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("student_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "subscription", fields: ["student_id"], references: ["id"], onDelete: "Cascade" }
                },
                status: {
                    name: "status",
                    type: "String",
                    optional: true
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }],
                    default: ExpressionUtils.call("now")
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }]
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id"), ExpressionUtils.field("student_id")]) }] }
            ],
            idFields: ["problem_set_id", "student_id"],
            uniqueFields: {
                problem_set_id_student_id: { problem_set_id: { type: "String" }, student_id: { type: "String" } }
            }
        },
        Teacher: {
            name: "Teacher",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }],
                    default: ExpressionUtils.call("uuid"),
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "teacher", fields: ["id"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    array: true,
                    relation: { opposite: "owner" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        TeacherList: {
            name: "TeacherList",
            fields: {
                email: {
                    name: "email",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                }
            },
            idFields: ["email"],
            uniqueFields: {
                email: { type: "String" }
            }
        },
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }],
                    default: ExpressionUtils.call("uuid")
                },
                name: {
                    name: "name",
                    type: "String",
                    optional: true
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                emailVerified: {
                    name: "emailVerified",
                    type: "DateTime",
                    optional: true
                },
                image: {
                    name: "image",
                    type: "String",
                    optional: true
                },
                accounts: {
                    name: "accounts",
                    type: "Account",
                    array: true,
                    relation: { opposite: "user" }
                },
                sessions: {
                    name: "sessions",
                    type: "Session",
                    array: true,
                    relation: { opposite: "user" }
                },
                Authenticator: {
                    name: "Authenticator",
                    type: "Authenticator",
                    array: true,
                    relation: { opposite: "user" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                hasAcceptedTOS: {
                    name: "hasAcceptedTOS",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                student: {
                    name: "student",
                    type: "Student",
                    optional: true,
                    relation: { opposite: "user" }
                },
                teacher: {
                    name: "teacher",
                    type: "Teacher",
                    optional: true,
                    relation: { opposite: "user" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Account: {
            name: "Account",
            fields: {
                userId: {
                    name: "userId",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "user"
                    ]
                },
                type: {
                    name: "type",
                    type: "String"
                },
                provider: {
                    name: "provider",
                    type: "String",
                    id: true
                },
                providerAccountId: {
                    name: "providerAccountId",
                    type: "String",
                    id: true
                },
                refresh_token: {
                    name: "refresh_token",
                    type: "String",
                    optional: true
                },
                access_token: {
                    name: "access_token",
                    type: "String",
                    optional: true
                },
                expires_at: {
                    name: "expires_at",
                    type: "Int",
                    optional: true
                },
                token_type: {
                    name: "token_type",
                    type: "String",
                    optional: true
                },
                scope: {
                    name: "scope",
                    type: "String",
                    optional: true
                },
                id_token: {
                    name: "id_token",
                    type: "String",
                    optional: true
                },
                session_state: {
                    name: "session_state",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "accounts", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("provider"), ExpressionUtils.field("providerAccountId")]) }] }
            ],
            idFields: ["provider", "providerAccountId"],
            uniqueFields: {
                provider_providerAccountId: { provider: { type: "String" }, providerAccountId: { type: "String" } }
            }
        },
        Session: {
            name: "Session",
            fields: {
                sessionToken: {
                    name: "sessionToken",
                    type: "String",
                    id: true,
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "user"
                    ]
                },
                expires: {
                    name: "expires",
                    type: "DateTime"
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "sessions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                }
            },
            idFields: ["sessionToken"],
            uniqueFields: {
                sessionToken: { type: "String" }
            }
        },
        VerificationToken: {
            name: "VerificationToken",
            fields: {
                identifier: {
                    name: "identifier",
                    type: "String",
                    id: true
                },
                token: {
                    name: "token",
                    type: "String",
                    id: true
                },
                expires: {
                    name: "expires",
                    type: "DateTime"
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("identifier"), ExpressionUtils.field("token")]) }] }
            ],
            idFields: ["identifier", "token"],
            uniqueFields: {
                identifier_token: { identifier: { type: "String" }, token: { type: "String" } }
            }
        },
        Authenticator: {
            name: "Authenticator",
            fields: {
                credentialID: {
                    name: "credentialID",
                    type: "String",
                    id: true,
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }],
                    foreignKeyFor: [
                        "user"
                    ]
                },
                providerAccountId: {
                    name: "providerAccountId",
                    type: "String"
                },
                credentialPublicKey: {
                    name: "credentialPublicKey",
                    type: "String"
                },
                counter: {
                    name: "counter",
                    type: "Int"
                },
                credentialDeviceType: {
                    name: "credentialDeviceType",
                    type: "String"
                },
                credentialBackedUp: {
                    name: "credentialBackedUp",
                    type: "Boolean"
                },
                transports: {
                    name: "transports",
                    type: "String",
                    optional: true
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "Authenticator", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId"), ExpressionUtils.field("credentialID")]) }] }
            ],
            idFields: ["credentialID", "userId"],
            uniqueFields: {
                credentialID: { type: "String" },
                userId_credentialID: { userId: { type: "String" }, credentialID: { type: "String" } }
            }
        }
    } as const;
    typeDefs = {
        CType: {
            name: "CType",
            fields: {
                base: {
                    name: "base",
                    type: "BaseType"
                },
                signed: {
                    name: "signed",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }],
                    default: true
                },
                sizeModifier: {
                    name: "sizeModifier",
                    type: "SizeModifier",
                    optional: true
                },
                arrayDimensions: {
                    name: "arrayDimensions",
                    type: "Int",
                    optional: true,
                    array: true
                },
                isPointer: {
                    name: "isPointer",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                isString: {
                    name: "isString",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                }
            },
            attributes: [
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("INT")), "||", ExpressionUtils.binary(ExpressionUtils.field("sizeModifier"), "==", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("Size modifier only applies to int") }] },
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("INT")), "||", ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("CHAR"))), "||", ExpressionUtils.binary(ExpressionUtils.field("signed"), "==", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("Signedness only applies to int or char") }] },
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("CHAR")), "||", ExpressionUtils.binary(ExpressionUtils.field("isString"), "==", ExpressionUtils.literal(true))), "||", ExpressionUtils.binary(ExpressionUtils.field("isString"), "==", ExpressionUtils.literal(false))) }, { name: "message", value: ExpressionUtils.literal("isString only applies to char") }] },
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("CHAR")), "||", ExpressionUtils.binary(ExpressionUtils.field("isString"), "==", ExpressionUtils.literal(false))), "||", ExpressionUtils.binary(ExpressionUtils.field("isString"), "==", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("isString only applies to char") }] }
            ]
        },
        CTypeWithValue: {
            name: "CTypeWithValue",
            fields: {
                base: {
                    name: "base",
                    type: "BaseType"
                },
                signed: {
                    name: "signed",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }],
                    default: true
                },
                sizeModifier: {
                    name: "sizeModifier",
                    type: "SizeModifier",
                    optional: true
                },
                arrayDimensions: {
                    name: "arrayDimensions",
                    type: "Int",
                    optional: true,
                    array: true
                },
                isPointer: {
                    name: "isPointer",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                isString: {
                    name: "isString",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                value: {
                    name: "value",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }],
                    default: ""
                }
            },
            attributes: [
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("INT")), "||", ExpressionUtils.binary(ExpressionUtils.field("sizeModifier"), "==", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("Size modifier only applies to int") }] },
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("INT")), "||", ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("CHAR"))), "||", ExpressionUtils.binary(ExpressionUtils.field("signed"), "==", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("Signedness only applies to int or char") }] },
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("CHAR")), "||", ExpressionUtils.binary(ExpressionUtils.field("isString"), "==", ExpressionUtils.literal(true))), "||", ExpressionUtils.binary(ExpressionUtils.field("isString"), "==", ExpressionUtils.literal(false))) }, { name: "message", value: ExpressionUtils.literal("isString only applies to char") }] },
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("CHAR")), "||", ExpressionUtils.binary(ExpressionUtils.field("isString"), "==", ExpressionUtils.literal(false))), "||", ExpressionUtils.binary(ExpressionUtils.field("isString"), "==", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("isString only applies to char") }] }
            ]
        }
    } as const;
    enums = {
        Language: {
            name: "Language",
            values: {
                C: "C"
            }
        },
        ProblemTestCaseType: {
            name: "ProblemTestCaseType",
            values: {
                FunctionOutputTestCase: "FunctionOutputTestCase",
                ProgramIOTestCase: "ProgramIOTestCase",
                CustomTestCase: "CustomTestCase"
            }
        },
        ProblemTestCaseOperator: {
            name: "ProblemTestCaseOperator",
            values: {
                EQUAL: "EQUAL",
                NOT_EQUAL: "NOT_EQUAL",
                LESS_THAN: "LESS_THAN",
                LESS_THAN_EQUAL: "LESS_THAN_EQUAL",
                GREATER_THAN: "GREATER_THAN",
                GREATER_THAN_EQUAL: "GREATER_THAN_EQUAL",
                WITHIN_RANGE: "WITHIN_RANGE",
                LEVENSHTEIN_SIMILARITY: "LEVENSHTEIN_SIMILARITY"
            }
        },
        BaseType: {
            name: "BaseType",
            values: {
                INT: "INT",
                CHAR: "CHAR",
                BOOL: "BOOL",
                FLOAT: "FLOAT",
                DOUBLE: "DOUBLE"
            }
        },
        SizeModifier: {
            name: "SizeModifier",
            values: {
                LONG: "LONG",
                LONG_LONG: "LONG_LONG",
                SHORT: "SHORT"
            }
        },
        HistoryEntryType: {
            name: "HistoryEntryType",
            values: {
                TEXT_MODIFIED: "TEXT_MODIFIED",
                PAGE_OPENED: "PAGE_OPENED",
                PAGE_FOCUS: "PAGE_FOCUS",
                RUN_ATTEMPT: "RUN_ATTEMPT",
                PING: "PING",
                OTHER: "OTHER"
            }
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
