//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult, TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type PracticeSession = $ModelResult<$Schema, "PracticeSession">;
export type PracticeHistoryEntry = $ModelResult<$Schema, "PracticeHistoryEntry">;
export type ProblemTopic = $ModelResult<$Schema, "ProblemTopic">;
export type Problem = $ModelResult<$Schema, "Problem">;
export type ProblemTestCase = $ModelResult<$Schema, "ProblemTestCase">;
export type FunctionOutputTestCase = $ModelResult<$Schema, "FunctionOutputTestCase">;
export type ProgramIOTestCase = $ModelResult<$Schema, "ProgramIOTestCase">;
export type CustomTestCase = $ModelResult<$Schema, "CustomTestCase">;
export type ProblemSetTopic = $ModelResult<$Schema, "ProblemSetTopic">;
export type ProblemSet = $ModelResult<$Schema, "ProblemSet">;
export type ProblemSetBookmark = $ModelResult<$Schema, "ProblemSetBookmark">;
export type ProblemSetCollaborator = $ModelResult<$Schema, "ProblemSetCollaborator">;
export type Subscription = $ModelResult<$Schema, "Subscription">;
export type SubjectTag = $ModelResult<$Schema, "SubjectTag">;
export type DifficultyTag = $ModelResult<$Schema, "DifficultyTag">;
export type TopicTag = $ModelResult<$Schema, "TopicTag">;
export type Student = $ModelResult<$Schema, "Student">;
export type Teacher = $ModelResult<$Schema, "Teacher">;
export type TeacherList = $ModelResult<$Schema, "TeacherList">;
export type User = $ModelResult<$Schema, "User">;
export type Account = $ModelResult<$Schema, "Account">;
export type Session = $ModelResult<$Schema, "Session">;
export type VerificationToken = $ModelResult<$Schema, "VerificationToken">;
export type Authenticator = $ModelResult<$Schema, "Authenticator">;
export type DataTypeWithValue = $TypeDefResult<$Schema, "DataTypeWithValue">;
export type Parameter = $TypeDefResult<$Schema, "Parameter">;
export type Comparison = $TypeDefResult<$Schema, "Comparison">;
export type Tag = $TypeDefResult<$Schema, "Tag">;
export const HistoryEntryType = $schema.enums.HistoryEntryType.values;
export type HistoryEntryType = (typeof HistoryEntryType)[keyof typeof HistoryEntryType];
export const Language = $schema.enums.Language.values;
export type Language = (typeof Language)[keyof typeof Language];
export const ProblemTestCaseType = $schema.enums.ProblemTestCaseType.values;
export type ProblemTestCaseType = (typeof ProblemTestCaseType)[keyof typeof ProblemTestCaseType];
export const FunctionOutputTestCaseOperator = $schema.enums.FunctionOutputTestCaseOperator.values;
export type FunctionOutputTestCaseOperator = (typeof FunctionOutputTestCaseOperator)[keyof typeof FunctionOutputTestCaseOperator];
export const TagType = $schema.enums.TagType.values;
export type TagType = (typeof TagType)[keyof typeof TagType];
export const TagColor = $schema.enums.TagColor.values;
export type TagColor = (typeof TagColor)[keyof typeof TagColor];
