//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult, TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type ProblemTag = $ModelResult<$Schema, "ProblemTag">;
export type Problem = $ModelResult<$Schema, "Problem">;
export type ProblemTestCase = $ModelResult<$Schema, "ProblemTestCase">;
export type FunctionOutputTestCase = $ModelResult<$Schema, "FunctionOutputTestCase">;
export type ProgramIOTestCase = $ModelResult<$Schema, "ProgramIOTestCase">;
export type CustomTestCase = $ModelResult<$Schema, "CustomTestCase">;
export type Tag = $ModelResult<$Schema, "Tag">;
export type ProblemSetTag = $ModelResult<$Schema, "ProblemSetTag">;
export type ProblemSet = $ModelResult<$Schema, "ProblemSet">;
export type PracticeSession = $ModelResult<$Schema, "PracticeSession">;
export type PracticeHistoryEntry = $ModelResult<$Schema, "PracticeHistoryEntry">;
export type Student = $ModelResult<$Schema, "Student">;
export type Subscription = $ModelResult<$Schema, "Subscription">;
export type Teacher = $ModelResult<$Schema, "Teacher">;
export type TeacherList = $ModelResult<$Schema, "TeacherList">;
export type User = $ModelResult<$Schema, "User">;
export type Account = $ModelResult<$Schema, "Account">;
export type Session = $ModelResult<$Schema, "Session">;
export type VerificationToken = $ModelResult<$Schema, "VerificationToken">;
export type Authenticator = $ModelResult<$Schema, "Authenticator">;
export type CType = $TypeDefResult<$Schema, "CType">;
export type CTypeWithValue = $TypeDefResult<$Schema, "CTypeWithValue">;
export const Language = $schema.enums.Language.values;
export type Language = (typeof Language)[keyof typeof Language];
export const ProblemTestCaseType = $schema.enums.ProblemTestCaseType.values;
export type ProblemTestCaseType = (typeof ProblemTestCaseType)[keyof typeof ProblemTestCaseType];
export const ProblemTestCaseOperator = $schema.enums.ProblemTestCaseOperator.values;
export type ProblemTestCaseOperator = (typeof ProblemTestCaseOperator)[keyof typeof ProblemTestCaseOperator];
export const BaseType = $schema.enums.BaseType.values;
export type BaseType = (typeof BaseType)[keyof typeof BaseType];
export const SizeModifier = $schema.enums.SizeModifier.values;
export type SizeModifier = (typeof SizeModifier)[keyof typeof SizeModifier];
export const TagType = $schema.enums.TagType.values;
export type TagType = (typeof TagType)[keyof typeof TagType];
export const TagColor = $schema.enums.TagColor.values;
export type TagColor = (typeof TagColor)[keyof typeof TagColor];
export const HistoryEntryType = $schema.enums.HistoryEntryType.values;
export type HistoryEntryType = (typeof HistoryEntryType)[keyof typeof HistoryEntryType];
