//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type AttributeApplication, type FieldDefault, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        PracticeSession: {
            name: "PracticeSession",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem"
                    ] as readonly string[]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "practice_sessions", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                student_id: {
                    name: "student_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "student"
                    ] as readonly string[]
                },
                student: {
                    name: "student",
                    type: "Student",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("student_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "practice_sessions", fields: ["student_id"], references: ["id"], onDelete: "Cascade" }
                },
                done: {
                    name: "done",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                previous_state: {
                    name: "previous_state",
                    type: "Json",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                practice_history_entries: {
                    name: "practice_history_entries",
                    type: "SessionHistoryEntry",
                    array: true,
                    relation: { opposite: "practice_session" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        SessionHistoryEntry: {
            name: "SessionHistoryEntry",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                timestamp: {
                    name: "timestamp",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "String"
                },
                data: {
                    name: "data",
                    type: "Json"
                },
                practice_session_id: {
                    name: "practice_session_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "practice_session"
                    ] as readonly string[]
                },
                practice_session: {
                    name: "practice_session",
                    type: "PracticeSession",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("practice_session_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "practice_history_entries", fields: ["practice_session_id"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProblemTopic: {
            name: "ProblemTopic",
            fields: {
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem"
                    ] as readonly string[]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "topics", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                tag_id: {
                    name: "tag_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "tag"
                    ] as readonly string[]
                },
                tag: {
                    name: "tag",
                    type: "TopicTag",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tag_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "topic_problems", fields: ["tag_id"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id"), ExpressionUtils.field("tag_id")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["problem_id", "tag_id"],
            uniqueFields: {
                problem_id_tag_id: { problem_id: { type: "String" }, tag_id: { type: "String" } }
            }
        },
        Problem: {
            name: "Problem",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                description: {
                    name: "description",
                    type: "String"
                },
                language: {
                    name: "language",
                    type: "Language",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("C") }] }] as readonly AttributeApplication[],
                    default: "C" as FieldDefault
                },
                starter_code: {
                    name: "starter_code",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }] as readonly AttributeApplication[],
                    default: "" as FieldDefault
                },
                visible: {
                    name: "visible",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }] as readonly AttributeApplication[],
                    default: true as FieldDefault
                },
                uses_slots: {
                    name: "uses_slots",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                difficulty_id: {
                    name: "difficulty_id",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "difficulty"
                    ] as readonly string[]
                },
                difficulty: {
                    name: "difficulty",
                    type: "DifficultyTag",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("difficulty_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "difficulty_problems", fields: ["difficulty_id"], references: ["id"], onDelete: "SetNull" }
                },
                subject_id: {
                    name: "subject_id",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "subject"
                    ] as readonly string[]
                },
                subject: {
                    name: "subject",
                    type: "SubjectTag",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("subject_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "subject_problems", fields: ["subject_id"], references: ["id"], onDelete: "SetNull" }
                },
                topics: {
                    name: "topics",
                    type: "ProblemTopic",
                    array: true,
                    relation: { opposite: "problem" }
                },
                extension_data: {
                    name: "extension_data",
                    type: "Json",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{}") }] }] as readonly AttributeApplication[],
                    default: "{}" as FieldDefault
                },
                problem_set_id: {
                    name: "problem_set_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem_set"
                    ] as readonly string[]
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "problems", fields: ["problem_set_id"], references: ["id"], onDelete: "Cascade" }
                },
                practice_sessions: {
                    name: "practice_sessions",
                    type: "PracticeSession",
                    array: true,
                    relation: { opposite: "problem" }
                },
                test_cases: {
                    name: "test_cases",
                    type: "ProblemTestCase",
                    array: true,
                    relation: { opposite: "problem" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProblemTestCase: {
            name: "ProblemTestCase",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "String"
                },
                public: {
                    name: "public",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }] as readonly AttributeApplication[],
                    default: true as FieldDefault
                },
                data: {
                    name: "data",
                    type: "Json"
                },
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem"
                    ] as readonly string[]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "test_cases", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProblemSetTopic: {
            name: "ProblemSetTopic",
            fields: {
                problem_set_id: {
                    name: "problem_set_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem_set"
                    ] as readonly string[]
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "topics", fields: ["problem_set_id"], references: ["id"], onDelete: "Cascade" }
                },
                topic_tag_id: {
                    name: "topic_tag_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "topic_tag"
                    ] as readonly string[]
                },
                topic_tag: {
                    name: "topic_tag",
                    type: "TopicTag",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("topic_tag_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "topic_problem_sets", fields: ["topic_tag_id"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id"), ExpressionUtils.field("topic_tag_id")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["problem_set_id", "topic_tag_id"],
            uniqueFields: {
                problem_set_id_topic_tag_id: { problem_set_id: { type: "String" }, topic_tag_id: { type: "String" } }
            }
        },
        ProblemSet: {
            name: "ProblemSet",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                description: {
                    name: "description",
                    type: "String",
                    optional: true
                },
                title: {
                    name: "title",
                    type: "String"
                },
                auto_accept: {
                    name: "auto_accept",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                is_global: {
                    name: "is_global",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                difficulty_id: {
                    name: "difficulty_id",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "difficulty"
                    ] as readonly string[]
                },
                difficulty: {
                    name: "difficulty",
                    type: "DifficultyTag",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("difficulty_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "difficulty_problem_sets", fields: ["difficulty_id"], references: ["id"], onDelete: "SetNull" }
                },
                subject_id: {
                    name: "subject_id",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "subject"
                    ] as readonly string[]
                },
                subject: {
                    name: "subject",
                    type: "SubjectTag",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("subject_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "subject_problem_sets", fields: ["subject_id"], references: ["id"], onDelete: "SetNull" }
                },
                topics: {
                    name: "topics",
                    type: "ProblemSetTopic",
                    array: true,
                    relation: { opposite: "problem_set" }
                },
                problems: {
                    name: "problems",
                    type: "Problem",
                    array: true,
                    relation: { opposite: "problem_set" }
                },
                subscriptions: {
                    name: "subscriptions",
                    type: "Subscription",
                    array: true,
                    relation: { opposite: "problem_set" }
                },
                bookmarks: {
                    name: "bookmarks",
                    type: "ProblemSetBookmark",
                    array: true,
                    relation: { opposite: "problem_set" }
                },
                extensions: {
                    name: "extensions",
                    type: "ProblemSetExtension",
                    array: true,
                    relation: { opposite: "problem_set" }
                },
                collaborators: {
                    name: "collaborators",
                    type: "ProblemSetCollaborator",
                    array: true,
                    relation: { opposite: "problem_set" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProblemSetExtension: {
            name: "ProblemSetExtension",
            fields: {
                problem_set_id: {
                    name: "problem_set_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem_set"
                    ] as readonly string[]
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "extensions", fields: ["problem_set_id"], references: ["id"] }
                },
                extension_id: {
                    name: "extension_id",
                    type: "String",
                    id: true
                },
                data: {
                    name: "data",
                    type: "Json"
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id"), ExpressionUtils.field("extension_id")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["problem_set_id", "extension_id"],
            uniqueFields: {
                problem_set_id_extension_id: { problem_set_id: { type: "String" }, extension_id: { type: "String" } }
            }
        },
        ProblemSetBookmark: {
            name: "ProblemSetBookmark",
            fields: {
                user_id: {
                    name: "user_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("user_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "bookmarks", fields: ["user_id"], references: ["id"], onDelete: "Cascade" }
                },
                problem_set_id: {
                    name: "problem_set_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem_set"
                    ] as readonly string[]
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "bookmarks", fields: ["problem_set_id"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id"), ExpressionUtils.field("user_id")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["user_id", "problem_set_id"],
            uniqueFields: {
                problem_set_id_user_id: { problem_set_id: { type: "String" }, user_id: { type: "String" } }
            }
        },
        ProblemSetCollaborator: {
            name: "ProblemSetCollaborator",
            fields: {
                collaborator_id: {
                    name: "collaborator_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "collaborator"
                    ] as readonly string[]
                },
                collaborator: {
                    name: "collaborator",
                    type: "Teacher",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("collaborator_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "problem_set_collaborations", fields: ["collaborator_id"], references: ["id"], onDelete: "Cascade" }
                },
                problem_set_id: {
                    name: "problem_set_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem_set"
                    ] as readonly string[]
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "collaborators", fields: ["problem_set_id"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("collaborator_id"), ExpressionUtils.field("problem_set_id")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["collaborator_id", "problem_set_id"],
            uniqueFields: {
                collaborator_id_problem_set_id: { collaborator_id: { type: "String" }, problem_set_id: { type: "String" } }
            }
        },
        Subscription: {
            name: "Subscription",
            fields: {
                problem_set_id: {
                    name: "problem_set_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem_set"
                    ] as readonly string[]
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "subscriptions", fields: ["problem_set_id"], references: ["id"], onDelete: "Cascade" }
                },
                student_id: {
                    name: "student_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "student"
                    ] as readonly string[]
                },
                student: {
                    name: "student",
                    type: "Student",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("student_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "subscription", fields: ["student_id"], references: ["id"], onDelete: "Cascade" }
                },
                status: {
                    name: "status",
                    type: "String",
                    optional: true
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id"), ExpressionUtils.field("student_id")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["problem_set_id", "student_id"],
            uniqueFields: {
                problem_set_id_student_id: { problem_set_id: { type: "String" }, student_id: { type: "String" } }
            }
        },
        Tag: {
            name: "Tag",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "TagType",
                    isDiscriminator: true
                },
                label: {
                    name: "label",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                order: {
                    name: "order",
                    type: "Int",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                }
            },
            attributes: [
                { name: "@@delegate", args: [{ name: "discriminator", value: ExpressionUtils.field("type") }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                label: { type: "String" }
            },
            isDelegate: true,
            subModels: ["SubjectTag", "DifficultyTag", "TopicTag"]
        },
        SubjectTag: {
            name: "SubjectTag",
            baseModel: "Tag",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "TagType",
                    originModel: "Tag",
                    isDiscriminator: true
                },
                label: {
                    name: "label",
                    type: "String",
                    unique: true,
                    originModel: "Tag",
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                order: {
                    name: "order",
                    type: "Int",
                    originModel: "Tag",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                subject_problems: {
                    name: "subject_problems",
                    type: "Problem",
                    array: true,
                    relation: { opposite: "subject" }
                },
                subject_problem_sets: {
                    name: "subject_problem_sets",
                    type: "ProblemSet",
                    array: true,
                    relation: { opposite: "subject" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                label: { type: "String" }
            }
        },
        DifficultyTag: {
            name: "DifficultyTag",
            baseModel: "Tag",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "TagType",
                    originModel: "Tag",
                    isDiscriminator: true
                },
                label: {
                    name: "label",
                    type: "String",
                    unique: true,
                    originModel: "Tag",
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                order: {
                    name: "order",
                    type: "Int",
                    originModel: "Tag",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                difficulty_problems: {
                    name: "difficulty_problems",
                    type: "Problem",
                    array: true,
                    relation: { opposite: "difficulty" }
                },
                difficulty_problem_sets: {
                    name: "difficulty_problem_sets",
                    type: "ProblemSet",
                    array: true,
                    relation: { opposite: "difficulty" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                label: { type: "String" }
            }
        },
        TopicTag: {
            name: "TopicTag",
            baseModel: "Tag",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "TagType",
                    originModel: "Tag",
                    isDiscriminator: true
                },
                label: {
                    name: "label",
                    type: "String",
                    unique: true,
                    originModel: "Tag",
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                order: {
                    name: "order",
                    type: "Int",
                    originModel: "Tag",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                topic_problems: {
                    name: "topic_problems",
                    type: "ProblemTopic",
                    array: true,
                    relation: { opposite: "tag" }
                },
                topic_problem_sets: {
                    name: "topic_problem_sets",
                    type: "ProblemSetTopic",
                    array: true,
                    relation: { opposite: "topic_tag" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                label: { type: "String" }
            }
        },
        Student: {
            name: "Student",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault,
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "student", fields: ["id"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                practice_sessions: {
                    name: "practice_sessions",
                    type: "PracticeSession",
                    array: true,
                    relation: { opposite: "student" }
                },
                subscription: {
                    name: "subscription",
                    type: "Subscription",
                    array: true,
                    relation: { opposite: "student" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Teacher: {
            name: "Teacher",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault,
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "teacher", fields: ["id"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                problem_set_collaborations: {
                    name: "problem_set_collaborations",
                    type: "ProblemSetCollaborator",
                    array: true,
                    relation: { opposite: "collaborator" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        TeacherList: {
            name: "TeacherList",
            fields: {
                email: {
                    name: "email",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                }
            },
            idFields: ["email"],
            uniqueFields: {
                email: { type: "String" }
            }
        },
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String",
                    optional: true
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                emailVerified: {
                    name: "emailVerified",
                    type: "DateTime",
                    optional: true
                },
                image: {
                    name: "image",
                    type: "String",
                    optional: true
                },
                accounts: {
                    name: "accounts",
                    type: "Account",
                    array: true,
                    relation: { opposite: "user" }
                },
                sessions: {
                    name: "sessions",
                    type: "Session",
                    array: true,
                    relation: { opposite: "user" }
                },
                Authenticator: {
                    name: "Authenticator",
                    type: "Authenticator",
                    array: true,
                    relation: { opposite: "user" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                },
                hasAcceptedTOS: {
                    name: "hasAcceptedTOS",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                student: {
                    name: "student",
                    type: "Student",
                    optional: true,
                    relation: { opposite: "user" }
                },
                teacher: {
                    name: "teacher",
                    type: "Teacher",
                    optional: true,
                    relation: { opposite: "user" }
                },
                bookmarks: {
                    name: "bookmarks",
                    type: "ProblemSetBookmark",
                    array: true,
                    relation: { opposite: "user" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Account: {
            name: "Account",
            fields: {
                userId: {
                    name: "userId",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                type: {
                    name: "type",
                    type: "String"
                },
                provider: {
                    name: "provider",
                    type: "String",
                    id: true
                },
                providerAccountId: {
                    name: "providerAccountId",
                    type: "String",
                    id: true
                },
                refresh_token: {
                    name: "refresh_token",
                    type: "String",
                    optional: true
                },
                access_token: {
                    name: "access_token",
                    type: "String",
                    optional: true
                },
                expires_at: {
                    name: "expires_at",
                    type: "Int",
                    optional: true
                },
                token_type: {
                    name: "token_type",
                    type: "String",
                    optional: true
                },
                scope: {
                    name: "scope",
                    type: "String",
                    optional: true
                },
                id_token: {
                    name: "id_token",
                    type: "String",
                    optional: true
                },
                session_state: {
                    name: "session_state",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "accounts", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("provider"), ExpressionUtils.field("providerAccountId")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["provider", "providerAccountId"],
            uniqueFields: {
                provider_providerAccountId: { provider: { type: "String" }, providerAccountId: { type: "String" } }
            }
        },
        Session: {
            name: "Session",
            fields: {
                sessionToken: {
                    name: "sessionToken",
                    type: "String",
                    id: true,
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                expires: {
                    name: "expires",
                    type: "DateTime"
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "sessions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            },
            idFields: ["sessionToken"],
            uniqueFields: {
                sessionToken: { type: "String" }
            }
        },
        VerificationToken: {
            name: "VerificationToken",
            fields: {
                identifier: {
                    name: "identifier",
                    type: "String",
                    id: true
                },
                token: {
                    name: "token",
                    type: "String",
                    id: true
                },
                expires: {
                    name: "expires",
                    type: "DateTime"
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("identifier"), ExpressionUtils.field("token")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["identifier", "token"],
            uniqueFields: {
                identifier_token: { identifier: { type: "String" }, token: { type: "String" } }
            }
        },
        Authenticator: {
            name: "Authenticator",
            fields: {
                credentialID: {
                    name: "credentialID",
                    type: "String",
                    id: true,
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                providerAccountId: {
                    name: "providerAccountId",
                    type: "String"
                },
                credentialPublicKey: {
                    name: "credentialPublicKey",
                    type: "String"
                },
                counter: {
                    name: "counter",
                    type: "Int"
                },
                credentialDeviceType: {
                    name: "credentialDeviceType",
                    type: "String"
                },
                credentialBackedUp: {
                    name: "credentialBackedUp",
                    type: "Boolean"
                },
                transports: {
                    name: "transports",
                    type: "String",
                    optional: true
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "Authenticator", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId"), ExpressionUtils.field("credentialID")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["credentialID", "userId"],
            uniqueFields: {
                credentialID: { type: "String" },
                userId_credentialID: { userId: { type: "String" }, credentialID: { type: "String" } }
            }
        }
    } as const;
    enums = {
        Language: {
            name: "Language",
            values: {
                C: "C"
            }
        },
        TagType: {
            name: "TagType",
            values: {
                SubjectTag: "SubjectTag",
                DifficultyTag: "DifficultyTag",
                TopicTag: "TopicTag"
            },
            fields: {
                SubjectTag: {
                    name: "SubjectTag",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("subject") }] }
                    ] as readonly AttributeApplication[]
                },
                DifficultyTag: {
                    name: "DifficultyTag",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("difficulty") }] }
                    ] as readonly AttributeApplication[]
                },
                TopicTag: {
                    name: "TopicTag",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("topic") }] }
                    ] as readonly AttributeApplication[]
                }
            }
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
