//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type AttributeApplication, type FieldDefault, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        PracticeSession: {
            name: "PracticeSession",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem"
                    ] as readonly string[]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "practice_sessions", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                student_id: {
                    name: "student_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "student"
                    ] as readonly string[]
                },
                student: {
                    name: "student",
                    type: "Student",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("student_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "practice_sessions", fields: ["student_id"], references: ["id"], onDelete: "Cascade" }
                },
                done: {
                    name: "done",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                previous_code: {
                    name: "previous_code",
                    type: "String"
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                practice_history_entries: {
                    name: "practice_history_entries",
                    type: "PracticeHistoryEntry",
                    array: true,
                    relation: { opposite: "practice_session" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        PracticeHistoryEntry: {
            name: "PracticeHistoryEntry",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                timestamp: {
                    name: "timestamp",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "HistoryEntryType"
                },
                data: {
                    name: "data",
                    type: "Json"
                },
                practice_session_id: {
                    name: "practice_session_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "practice_session"
                    ] as readonly string[]
                },
                practice_session: {
                    name: "practice_session",
                    type: "PracticeSession",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("practice_session_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "practice_history_entries", fields: ["practice_session_id"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProblemTopic: {
            name: "ProblemTopic",
            fields: {
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem"
                    ] as readonly string[]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "topics", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                tag_id: {
                    name: "tag_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "tag"
                    ] as readonly string[]
                },
                tag: {
                    name: "tag",
                    type: "TopicTag",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tag_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "problems", fields: ["tag_id"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id"), ExpressionUtils.field("tag_id")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["problem_id", "tag_id"],
            uniqueFields: {
                problem_id_tag_id: { problem_id: { type: "String" }, tag_id: { type: "String" } }
            }
        },
        Problem: {
            name: "Problem",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                description: {
                    name: "description",
                    type: "String"
                },
                language: {
                    name: "language",
                    type: "Language",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("C") }] }] as readonly AttributeApplication[],
                    default: "C" as FieldDefault
                },
                starter_code: {
                    name: "starter_code",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }] as readonly AttributeApplication[],
                    default: "" as FieldDefault
                },
                visible: {
                    name: "visible",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }] as readonly AttributeApplication[],
                    default: true as FieldDefault
                },
                difficulty_id: {
                    name: "difficulty_id",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "difficulty",
                        "subject"
                    ] as readonly string[]
                },
                difficulty: {
                    name: "difficulty",
                    type: "DifficultyTag",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("difficulty_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "problems", fields: ["difficulty_id"], references: ["id"], onDelete: "SetNull" }
                },
                subject_id: {
                    name: "subject_id",
                    type: "String",
                    optional: true
                },
                subject: {
                    name: "subject",
                    type: "SubjectTag",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("difficulty_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "problems", fields: ["difficulty_id"], references: ["id"], onDelete: "SetNull" }
                },
                topics: {
                    name: "topics",
                    type: "ProblemTopic",
                    array: true,
                    relation: { opposite: "problem" }
                },
                problem_set_id: {
                    name: "problem_set_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem_set"
                    ] as readonly string[]
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "problems", fields: ["problem_set_id"], references: ["id"], onDelete: "Cascade" }
                },
                practice_sessions: {
                    name: "practice_sessions",
                    type: "PracticeSession",
                    array: true,
                    relation: { opposite: "problem" }
                },
                test_cases: {
                    name: "test_cases",
                    type: "ProblemTestCase",
                    array: true,
                    relation: { opposite: "problem" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProblemTestCase: {
            name: "ProblemTestCase",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "ProblemTestCaseType",
                    isDiscriminator: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("FunctionOutputTestCase") }] }] as readonly AttributeApplication[],
                    default: "FunctionOutputTestCase" as FieldDefault
                },
                public: {
                    name: "public",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }] as readonly AttributeApplication[],
                    default: true as FieldDefault
                },
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem"
                    ] as readonly string[]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "test_cases", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@delegate", args: [{ name: "discriminator", value: ExpressionUtils.field("type") }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            },
            isDelegate: true,
            subModels: ["FunctionOutputTestCase", "ProgramIOTestCase", "CustomTestCase"]
        },
        FunctionOutputTestCase: {
            name: "FunctionOutputTestCase",
            baseModel: "ProblemTestCase",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "ProblemTestCaseType",
                    originModel: "ProblemTestCase",
                    isDiscriminator: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("FunctionOutputTestCase") }] }] as readonly AttributeApplication[],
                    default: "FunctionOutputTestCase" as FieldDefault
                },
                public: {
                    name: "public",
                    type: "Boolean",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }] as readonly AttributeApplication[],
                    default: true as FieldDefault
                },
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem"
                    ] as readonly string[]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "test_cases", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                parameters: {
                    name: "parameters",
                    type: "Parameter",
                    array: true,
                    attributes: [{ name: "@json" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("[]") }] }] as readonly AttributeApplication[],
                    default: "[]" as FieldDefault
                },
                comparisons: {
                    name: "comparisons",
                    type: "Comparison",
                    array: true,
                    attributes: [{ name: "@json" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("[]") }] }] as readonly AttributeApplication[],
                    default: "[]" as FieldDefault
                },
                return_type: {
                    name: "return_type",
                    type: "Parameter",
                    attributes: [{ name: "@json" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("{\"type\":\"int\", \"data\":{\"signed\":\"none\",\"value\": \"5\",\"size\": 32}}") }] }] as readonly AttributeApplication[],
                    default: "{\"type\":\"int\", \"data\":{\"signed\":\"none\",\"value\": \"5\",\"size\": 32}}" as FieldDefault
                },
                function_name: {
                    name: "function_name",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }] as readonly AttributeApplication[],
                    default: "" as FieldDefault
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProgramIOTestCase: {
            name: "ProgramIOTestCase",
            baseModel: "ProblemTestCase",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "ProblemTestCaseType",
                    originModel: "ProblemTestCase",
                    isDiscriminator: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("FunctionOutputTestCase") }] }] as readonly AttributeApplication[],
                    default: "FunctionOutputTestCase" as FieldDefault
                },
                public: {
                    name: "public",
                    type: "Boolean",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }] as readonly AttributeApplication[],
                    default: true as FieldDefault
                },
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem"
                    ] as readonly string[]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "test_cases", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                input: {
                    name: "input",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }] as readonly AttributeApplication[],
                    default: "" as FieldDefault
                },
                output: {
                    name: "output",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }] as readonly AttributeApplication[],
                    default: "" as FieldDefault
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        CustomTestCase: {
            name: "CustomTestCase",
            baseModel: "ProblemTestCase",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "ProblemTestCaseType",
                    originModel: "ProblemTestCase",
                    isDiscriminator: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("FunctionOutputTestCase") }] }] as readonly AttributeApplication[],
                    default: "FunctionOutputTestCase" as FieldDefault
                },
                public: {
                    name: "public",
                    type: "Boolean",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }] as readonly AttributeApplication[],
                    default: true as FieldDefault
                },
                problem_id: {
                    name: "problem_id",
                    type: "String",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem"
                    ] as readonly string[]
                },
                problem: {
                    name: "problem",
                    type: "Problem",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "test_cases", fields: ["problem_id"], references: ["id"], onDelete: "Cascade" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "ProblemTestCase",
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                },
                test_code: {
                    name: "test_code",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }] as readonly AttributeApplication[],
                    default: "" as FieldDefault
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProblemSetTopic: {
            name: "ProblemSetTopic",
            fields: {
                problem_set_id: {
                    name: "problem_set_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem_set"
                    ] as readonly string[]
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "topics", fields: ["problem_set_id"], references: ["id"], onDelete: "Cascade" }
                },
                topic_tag_id: {
                    name: "topic_tag_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "topic_tag"
                    ] as readonly string[]
                },
                topic_tag: {
                    name: "topic_tag",
                    type: "TopicTag",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("topic_tag_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "problem_sets", fields: ["topic_tag_id"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id"), ExpressionUtils.field("topic_tag_id")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["problem_set_id", "topic_tag_id"],
            uniqueFields: {
                problem_set_id_topic_tag_id: { problem_set_id: { type: "String" }, topic_tag_id: { type: "String" } }
            }
        },
        ProblemSet: {
            name: "ProblemSet",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                description: {
                    name: "description",
                    type: "String",
                    optional: true
                },
                title: {
                    name: "title",
                    type: "String"
                },
                auto_accept: {
                    name: "auto_accept",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                is_global: {
                    name: "is_global",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                difficulty_id: {
                    name: "difficulty_id",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "difficulty",
                        "subject"
                    ] as readonly string[]
                },
                difficulty: {
                    name: "difficulty",
                    type: "DifficultyTag",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("difficulty_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "problem_sets", fields: ["difficulty_id"], references: ["id"], onDelete: "SetNull" }
                },
                subject_id: {
                    name: "subject_id",
                    type: "String",
                    optional: true
                },
                subject: {
                    name: "subject",
                    type: "SubjectTag",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("difficulty_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "problem_sets", fields: ["difficulty_id"], references: ["id"], onDelete: "SetNull" }
                },
                topics: {
                    name: "topics",
                    type: "ProblemSetTopic",
                    array: true,
                    relation: { opposite: "problem_set" }
                },
                problems: {
                    name: "problems",
                    type: "Problem",
                    array: true,
                    relation: { opposite: "problem_set" }
                },
                subscriptions: {
                    name: "subscriptions",
                    type: "Subscription",
                    array: true,
                    relation: { opposite: "problem_set" }
                },
                collaborators: {
                    name: "collaborators",
                    type: "ProblemSetCollaborator",
                    array: true,
                    relation: { opposite: "problem_set" }
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ProblemSetCollaborator: {
            name: "ProblemSetCollaborator",
            fields: {
                collaborator_id: {
                    name: "collaborator_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "collaborator"
                    ] as readonly string[]
                },
                collaborator: {
                    name: "collaborator",
                    type: "Teacher",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("collaborator_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "problem_set_collaborations", fields: ["collaborator_id"], references: ["id"], onDelete: "Cascade" }
                },
                problem_set_id: {
                    name: "problem_set_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem_set"
                    ] as readonly string[]
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "collaborators", fields: ["problem_set_id"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("collaborator_id"), ExpressionUtils.field("problem_set_id")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["collaborator_id", "problem_set_id"],
            uniqueFields: {
                collaborator_id_problem_set_id: { collaborator_id: { type: "String" }, problem_set_id: { type: "String" } }
            }
        },
        Subscription: {
            name: "Subscription",
            fields: {
                problem_set_id: {
                    name: "problem_set_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "problem_set"
                    ] as readonly string[]
                },
                problem_set: {
                    name: "problem_set",
                    type: "ProblemSet",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "subscriptions", fields: ["problem_set_id"], references: ["id"], onDelete: "Cascade" }
                },
                student_id: {
                    name: "student_id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "student"
                    ] as readonly string[]
                },
                student: {
                    name: "student",
                    type: "Student",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("student_id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "subscription", fields: ["student_id"], references: ["id"], onDelete: "Cascade" }
                },
                status: {
                    name: "status",
                    type: "String",
                    optional: true
                },
                created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }, { name: "@db.Timestamptz", args: [{ name: "x", value: ExpressionUtils.literal(6) }] }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("problem_set_id"), ExpressionUtils.field("student_id")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["problem_set_id", "student_id"],
            uniqueFields: {
                problem_set_id_student_id: { problem_set_id: { type: "String" }, student_id: { type: "String" } }
            }
        },
        SubjectTag: {
            name: "SubjectTag",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "TagType"
                },
                color: {
                    name: "color",
                    type: "TagColor",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("TAG_COLOR_DEFAULT") }] }] as readonly AttributeApplication[],
                    default: "TAG_COLOR_DEFAULT" as FieldDefault
                },
                label: {
                    name: "label",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                order: {
                    name: "order",
                    type: "Int",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                problems: {
                    name: "problems",
                    type: "Problem",
                    array: true,
                    relation: { opposite: "subject" }
                },
                problem_sets: {
                    name: "problem_sets",
                    type: "ProblemSet",
                    array: true,
                    relation: { opposite: "subject" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                label: { type: "String" }
            }
        },
        DifficultyTag: {
            name: "DifficultyTag",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "TagType"
                },
                color: {
                    name: "color",
                    type: "TagColor",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("TAG_COLOR_DEFAULT") }] }] as readonly AttributeApplication[],
                    default: "TAG_COLOR_DEFAULT" as FieldDefault
                },
                label: {
                    name: "label",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                order: {
                    name: "order",
                    type: "Int",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                problems: {
                    name: "problems",
                    type: "Problem",
                    array: true,
                    relation: { opposite: "difficulty" }
                },
                problem_sets: {
                    name: "problem_sets",
                    type: "ProblemSet",
                    array: true,
                    relation: { opposite: "difficulty" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                label: { type: "String" }
            }
        },
        TopicTag: {
            name: "TopicTag",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "TagType"
                },
                color: {
                    name: "color",
                    type: "TagColor",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("TAG_COLOR_DEFAULT") }] }] as readonly AttributeApplication[],
                    default: "TAG_COLOR_DEFAULT" as FieldDefault
                },
                label: {
                    name: "label",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                order: {
                    name: "order",
                    type: "Int",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                },
                problems: {
                    name: "problems",
                    type: "ProblemTopic",
                    array: true,
                    relation: { opposite: "tag" }
                },
                problem_sets: {
                    name: "problem_sets",
                    type: "ProblemSetTopic",
                    array: true,
                    relation: { opposite: "topic_tag" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                label: { type: "String" }
            }
        },
        Student: {
            name: "Student",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault,
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "student", fields: ["id"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                practice_sessions: {
                    name: "practice_sessions",
                    type: "PracticeSession",
                    array: true,
                    relation: { opposite: "student" }
                },
                subscription: {
                    name: "subscription",
                    type: "Subscription",
                    array: true,
                    relation: { opposite: "student" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Teacher: {
            name: "Teacher",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault,
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "teacher", fields: ["id"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                problem_set_collaborations: {
                    name: "problem_set_collaborations",
                    type: "ProblemSetCollaborator",
                    array: true,
                    relation: { opposite: "collaborator" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        TeacherList: {
            name: "TeacherList",
            fields: {
                email: {
                    name: "email",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                }
            },
            idFields: ["email"],
            uniqueFields: {
                email: { type: "String" }
            }
        },
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String",
                    optional: true
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                emailVerified: {
                    name: "emailVerified",
                    type: "DateTime",
                    optional: true
                },
                image: {
                    name: "image",
                    type: "String",
                    optional: true
                },
                accounts: {
                    name: "accounts",
                    type: "Account",
                    array: true,
                    relation: { opposite: "user" }
                },
                sessions: {
                    name: "sessions",
                    type: "Session",
                    array: true,
                    relation: { opposite: "user" }
                },
                Authenticator: {
                    name: "Authenticator",
                    type: "Authenticator",
                    array: true,
                    relation: { opposite: "user" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                },
                hasAcceptedTOS: {
                    name: "hasAcceptedTOS",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                student: {
                    name: "student",
                    type: "Student",
                    optional: true,
                    relation: { opposite: "user" }
                },
                teacher: {
                    name: "teacher",
                    type: "Teacher",
                    optional: true,
                    relation: { opposite: "user" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Account: {
            name: "Account",
            fields: {
                userId: {
                    name: "userId",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                type: {
                    name: "type",
                    type: "String"
                },
                provider: {
                    name: "provider",
                    type: "String",
                    id: true
                },
                providerAccountId: {
                    name: "providerAccountId",
                    type: "String",
                    id: true
                },
                refresh_token: {
                    name: "refresh_token",
                    type: "String",
                    optional: true
                },
                access_token: {
                    name: "access_token",
                    type: "String",
                    optional: true
                },
                expires_at: {
                    name: "expires_at",
                    type: "Int",
                    optional: true
                },
                token_type: {
                    name: "token_type",
                    type: "String",
                    optional: true
                },
                scope: {
                    name: "scope",
                    type: "String",
                    optional: true
                },
                id_token: {
                    name: "id_token",
                    type: "String",
                    optional: true
                },
                session_state: {
                    name: "session_state",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "accounts", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("provider"), ExpressionUtils.field("providerAccountId")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["provider", "providerAccountId"],
            uniqueFields: {
                provider_providerAccountId: { provider: { type: "String" }, providerAccountId: { type: "String" } }
            }
        },
        Session: {
            name: "Session",
            fields: {
                sessionToken: {
                    name: "sessionToken",
                    type: "String",
                    id: true,
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                expires: {
                    name: "expires",
                    type: "DateTime"
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "sessions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            },
            idFields: ["sessionToken"],
            uniqueFields: {
                sessionToken: { type: "String" }
            }
        },
        VerificationToken: {
            name: "VerificationToken",
            fields: {
                identifier: {
                    name: "identifier",
                    type: "String",
                    id: true
                },
                token: {
                    name: "token",
                    type: "String",
                    id: true
                },
                expires: {
                    name: "expires",
                    type: "DateTime"
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("identifier"), ExpressionUtils.field("token")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["identifier", "token"],
            uniqueFields: {
                identifier_token: { identifier: { type: "String" }, token: { type: "String" } }
            }
        },
        Authenticator: {
            name: "Authenticator",
            fields: {
                credentialID: {
                    name: "credentialID",
                    type: "String",
                    id: true,
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@db.Uuid" }] as readonly AttributeApplication[],
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                providerAccountId: {
                    name: "providerAccountId",
                    type: "String"
                },
                credentialPublicKey: {
                    name: "credentialPublicKey",
                    type: "String"
                },
                counter: {
                    name: "counter",
                    type: "Int"
                },
                credentialDeviceType: {
                    name: "credentialDeviceType",
                    type: "String"
                },
                credentialBackedUp: {
                    name: "credentialBackedUp",
                    type: "Boolean"
                },
                transports: {
                    name: "transports",
                    type: "String",
                    optional: true
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "Authenticator", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId"), ExpressionUtils.field("credentialID")]) }] }
            ] as readonly AttributeApplication[],
            idFields: ["credentialID", "userId"],
            uniqueFields: {
                credentialID: { type: "String" },
                userId_credentialID: { userId: { type: "String" }, credentialID: { type: "String" } }
            }
        }
    } as const;
    typeDefs = {
        CType: {
            name: "CType",
            fields: {
                base: {
                    name: "base",
                    type: "BaseType"
                },
                signed: {
                    name: "signed",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }] as readonly AttributeApplication[],
                    default: true as FieldDefault
                },
                size_modifier: {
                    name: "size_modifier",
                    type: "SizeModifier",
                    optional: true
                },
                array_dimensions: {
                    name: "array_dimensions",
                    type: "Int",
                    optional: true,
                    array: true
                },
                is_pointer: {
                    name: "is_pointer",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                is_string: {
                    name: "is_string",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                }
            },
            attributes: [
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("INT")), "||", ExpressionUtils.binary(ExpressionUtils.field("size_modifier"), "==", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("Size modifier only applies to int") }] },
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("INT")), "||", ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("CHAR"))), "||", ExpressionUtils.binary(ExpressionUtils.field("signed"), "==", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("Signedness only applies to int or char") }] },
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("CHAR")), "||", ExpressionUtils.binary(ExpressionUtils.field("is_string"), "==", ExpressionUtils.literal(true))), "||", ExpressionUtils.binary(ExpressionUtils.field("is_string"), "==", ExpressionUtils.literal(false))) }, { name: "message", value: ExpressionUtils.literal("is_string only applies to char") }] },
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("CHAR")), "||", ExpressionUtils.binary(ExpressionUtils.field("is_string"), "==", ExpressionUtils.literal(false))), "||", ExpressionUtils.binary(ExpressionUtils.field("is_string"), "==", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("is_string only applies to char") }] }
            ] as readonly AttributeApplication[]
        },
        CTypeWithValue: {
            name: "CTypeWithValue",
            fields: {
                base: {
                    name: "base",
                    type: "BaseType"
                },
                signed: {
                    name: "signed",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }] as readonly AttributeApplication[],
                    default: true as FieldDefault
                },
                size_modifier: {
                    name: "size_modifier",
                    type: "SizeModifier",
                    optional: true
                },
                array_dimensions: {
                    name: "array_dimensions",
                    type: "Int",
                    optional: true,
                    array: true
                },
                is_pointer: {
                    name: "is_pointer",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                is_string: {
                    name: "is_string",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                value: {
                    name: "value",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }] as readonly AttributeApplication[],
                    default: "" as FieldDefault
                }
            },
            attributes: [
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("INT")), "||", ExpressionUtils.binary(ExpressionUtils.field("size_modifier"), "==", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("Size modifier only applies to int") }] },
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("INT")), "||", ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("CHAR"))), "||", ExpressionUtils.binary(ExpressionUtils.field("signed"), "==", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("Signedness only applies to int or char") }] },
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("CHAR")), "||", ExpressionUtils.binary(ExpressionUtils.field("is_string"), "==", ExpressionUtils.literal(true))), "||", ExpressionUtils.binary(ExpressionUtils.field("is_string"), "==", ExpressionUtils.literal(false))) }, { name: "message", value: ExpressionUtils.literal("is_string only applies to char") }] },
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("base"), "==", ExpressionUtils.literal("CHAR")), "||", ExpressionUtils.binary(ExpressionUtils.field("is_string"), "==", ExpressionUtils.literal(false))), "||", ExpressionUtils.binary(ExpressionUtils.field("is_string"), "==", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("is_string only applies to char") }] }
            ] as readonly AttributeApplication[]
        },
        DataTypeWithValue: {
            name: "DataTypeWithValue",
            fields: {
                type: {
                    name: "type",
                    type: "String"
                },
                data: {
                    name: "data",
                    type: "Json"
                }
            }
        },
        Parameter: {
            name: "Parameter",
            fields: {
                type: {
                    name: "type",
                    type: "String"
                },
                data: {
                    name: "data",
                    type: "Json"
                }
            }
        },
        Comparison: {
            name: "Comparison",
            fields: {
                type: {
                    name: "type",
                    type: "String"
                },
                data: {
                    name: "data",
                    type: "Json"
                },
                symbol: {
                    name: "symbol",
                    type: "String"
                },
                operator: {
                    name: "operator",
                    type: "FunctionOutputTestCaseOperator"
                },
                range_value: {
                    name: "range_value",
                    type: "String",
                    optional: true
                }
            },
            attributes: [
                { name: "@@validate", args: [{ name: "value", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("operator"), "!=", ExpressionUtils.literal("WITHIN_RANGE")), "||", ExpressionUtils.binary(ExpressionUtils.field("range_value"), "!=", ExpressionUtils._null())) }, { name: "message", value: ExpressionUtils.literal("range_value must be provided when operator is WITHIN_RANGE") }] }
            ] as readonly AttributeApplication[]
        },
        Tag: {
            name: "Tag",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }, { name: "@db.Uuid" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                type: {
                    name: "type",
                    type: "TagType"
                },
                color: {
                    name: "color",
                    type: "TagColor",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("TAG_COLOR_DEFAULT") }] }] as readonly AttributeApplication[],
                    default: "TAG_COLOR_DEFAULT" as FieldDefault
                },
                label: {
                    name: "label",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                order: {
                    name: "order",
                    type: "Int",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
                    default: 0 as FieldDefault
                }
            }
        }
    } as const;
    enums = {
        BaseType: {
            name: "BaseType",
            values: {
                INT: "INT",
                CHAR: "CHAR",
                BOOL: "BOOL",
                FLOAT: "FLOAT",
                DOUBLE: "DOUBLE"
            }
        },
        SizeModifier: {
            name: "SizeModifier",
            values: {
                LONG: "LONG",
                LONG_LONG: "LONG_LONG",
                SHORT: "SHORT"
            }
        },
        HistoryEntryType: {
            name: "HistoryEntryType",
            values: {
                TEXT_MODIFIED: "TEXT_MODIFIED",
                PAGE_OPENED: "PAGE_OPENED",
                PAGE_FOCUS: "PAGE_FOCUS",
                RUN_ATTEMPT: "RUN_ATTEMPT",
                PING: "PING",
                OTHER: "OTHER"
            }
        },
        Language: {
            name: "Language",
            values: {
                C: "C"
            }
        },
        ProblemTestCaseType: {
            name: "ProblemTestCaseType",
            values: {
                FunctionOutputTestCase: "FunctionOutputTestCase",
                ProgramIOTestCase: "ProgramIOTestCase",
                CustomTestCase: "CustomTestCase"
            }
        },
        FunctionOutputTestCaseOperator: {
            name: "FunctionOutputTestCaseOperator",
            values: {
                EQUAL: "EQUAL",
                NOT_EQUAL: "NOT_EQUAL",
                LESS_THAN: "LESS_THAN",
                LESS_THAN_EQUAL: "LESS_THAN_EQUAL",
                GREATER_THAN: "GREATER_THAN",
                GREATER_THAN_EQUAL: "GREATER_THAN_EQUAL",
                WITHIN_RANGE: "WITHIN_RANGE"
            }
        },
        TagType: {
            name: "TagType",
            values: {
                TAG_SUBJECT: "TAG_SUBJECT",
                TAG_DIFFICULTY: "TAG_DIFFICULTY",
                TAG_TOPIC: "TAG_TOPIC"
            },
            fields: {
                TAG_SUBJECT: {
                    name: "TAG_SUBJECT",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("subject") }] }
                    ] as readonly AttributeApplication[]
                },
                TAG_DIFFICULTY: {
                    name: "TAG_DIFFICULTY",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("difficulty") }] }
                    ] as readonly AttributeApplication[]
                },
                TAG_TOPIC: {
                    name: "TAG_TOPIC",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("topic") }] }
                    ] as readonly AttributeApplication[]
                }
            }
        },
        TagColor: {
            name: "TagColor",
            values: {
                TAG_COLOR_DEFAULT: "TAG_COLOR_DEFAULT",
                TAG_COLOR_PRIMARY: "TAG_COLOR_PRIMARY",
                TAG_COLOR_SECONDARY: "TAG_COLOR_SECONDARY",
                TAG_COLOR_ACCENT: "TAG_COLOR_ACCENT",
                TAG_COLOR_RED: "TAG_COLOR_RED",
                TAG_COLOR_YELLOW: "TAG_COLOR_YELLOW",
                TAG_COLOR_GREEN: "TAG_COLOR_GREEN",
                TAG_COLOR_BLUE: "TAG_COLOR_BLUE"
            },
            fields: {
                TAG_COLOR_DEFAULT: {
                    name: "TAG_COLOR_DEFAULT",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("default") }] }
                    ] as readonly AttributeApplication[]
                },
                TAG_COLOR_PRIMARY: {
                    name: "TAG_COLOR_PRIMARY",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("primary") }] }
                    ] as readonly AttributeApplication[]
                },
                TAG_COLOR_SECONDARY: {
                    name: "TAG_COLOR_SECONDARY",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("secondary") }] }
                    ] as readonly AttributeApplication[]
                },
                TAG_COLOR_ACCENT: {
                    name: "TAG_COLOR_ACCENT",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("accent") }] }
                    ] as readonly AttributeApplication[]
                },
                TAG_COLOR_RED: {
                    name: "TAG_COLOR_RED",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("red") }] }
                    ] as readonly AttributeApplication[]
                },
                TAG_COLOR_YELLOW: {
                    name: "TAG_COLOR_YELLOW",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("yellow") }] }
                    ] as readonly AttributeApplication[]
                },
                TAG_COLOR_GREEN: {
                    name: "TAG_COLOR_GREEN",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("green") }] }
                    ] as readonly AttributeApplication[]
                },
                TAG_COLOR_BLUE: {
                    name: "TAG_COLOR_BLUE",
                    attributes: [
                        { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("blue") }] }
                    ] as readonly AttributeApplication[]
                }
            }
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
